### ISSUE TITLE
Modul not Updating Status

### ISSUE THREAD

**Issue by Webmasterei** [Barzahlen/Barzahlen-Magento#2]
Hi,
we implemented the module and everything seems to run smootely so far. The only problem: We do not get status Updates upon Payment. 

Is this function implemented at all?

Regards

Bernhard

**Comment by martinseener** [comment]
Hi,
glad to hear that it run's just fine.

As for the status updates i expect you mean the push notifications we send back to the shop after we receive the payment. In that case you might want to have a look at the API's Webhooks part here: https://docs.barzahlen.de/api/v2/#webhooks

To sum it up, you need to define a live/production and/or a sandbox notification URL within your division in the https://controlcenter.barzahlen.de where you also got your api key.

If you have further questions, just ask us here or if you're implementing a real shop anyways you can also request support at https://integration.barzahlen.de/en/support#kontakt

I hope i could help you.
